language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
install:
  - composer install
script:
 - ./vendor/bin/phpunit --coverage-clover ./tests/Logs/clover.xml
after_script:
 - php vendor/bin/php-coveralls -v
